version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Deploy infrastructure
          command: |
            cd ./terraform/
            terraform apply -auto-approve
            cd ../ansible/
            ansible-playbook -i inventory main.yml
